### ISSUE TITLE
Mercury

### ISSUE THREAD

**Issue by iaferrer** [IIC2513-2015-2/syllabus#10]
Podemos usar la gema Mercury para que las personas puedan editar su CV desde nuestra página? o usar algo como Markdown o similares?

Gracias.

**Comment by lopezjurip** [comment]
Por mi, bien

**Comment by raulmt** [comment]
sí, pueden usar gemas para WYSIWYG editors. También para procesar markdown o similares.

**Comment by iaferrer** [comment]
Muchas gracias!
