### ISSUE TITLE
jQuery plugins

### ISSUE THREAD

**Issue by saratscheff** [IIC2513-2015-2/syllabus#12]
Hola, ¿Se pueden utilizar jQuery plugins como https://select2.github.io ?

Gracias!

**Comment by lopezjurip** [comment]
Sip

UPDATE: Pensé que lo habían posteado en el foro de otro ramo ( ͡° ͜ʖ ͡°)

**Comment by saratscheff** [comment]
Gracias por la pronta respuesta! 
¿Y el uso de una gema que lo integra para facilitar?
https://github.com/argerim/select2-rails

**Comment by lopezjurip** [comment]
Sí claro

**Comment by saratscheff** [comment]
Gracias!
