### ISSUE TITLE
API

### ISSUE THREAD

**Issue by ajleon** [IIC2513-2015-2/syllabus#13]
Se pueden usar las gemas de googleMaps para usar la API Directions??

Gracias!

**Comment by raulmt** [comment]
No. La idea es que lo hagan un poco más bajo nivel. No siempre tendrán una gema que haga todo por ustedes. A eso se refería esta parte del enunciado:

Nota importante: tengan presente que la idea es consumir una API REST mediante requests generados por ustedes en su aplicación (ya sea desde Ruby o desde el cliente con JavaScript)

**Comment by ajleon** [comment]
Ok, se puede utilizar la API oficial de JavaScript de GoogleMaps?
