### ISSUE TITLE
Ruby en Windows

### ISSUE THREAD

**Issue by fdoflorenzano** [IIC2513-2015-2/syllabus#4]
Hola! Quería saber si tienen alguna recomendación o ayuda para la instalación de Ruby en Windows, he intentado varias veces pero me confundo con tantas formas distintas de recursos y además soportan distintas versiones. ¿Cual es la mejor forma? Perdón lo perdido, aprecio la ayuda, saludos!

**Comment by lopezjurip** [comment]
Chocolatey!

``` sh
# https://chocolatey.org/packages?q=ruby
choco install ruby
```

Puedes encontrar una guía de como instalar Chocolatey en Windows en esta que escribí para Programación Avanzada (IIC2233): 
https://github.com/IIC2233-2015-2/syllabus/wiki/Windows

**Comment by ThomasHepner-zz** [comment]
Mira, cuando yo aprendí Rails empecé en Windows, y te digo de antemano que la experiencia fue nefasta. Te recomiendo 100% que instales alguna rendición de Linux en tu computador, eso facilitará algunas cosas. De todas maneras, cuando yo empecé seguí al pie de la letra esta guía (https://www.railstutorial.org/book/frontmatter), que te ayuda con el setup desde el principio (atento a las secciones, porque explican el setup para distintos SOs), y que te debería servir no sólo para Ruby, sino que para todo el entorno de trabajo en general.

**Comment by fdoflorenzano** [comment]
Gracias! Por progra tenía chocolatey jaja grande pato.
Y he escuchado harto eso. Voy a averiguar la mejor forma para ojala no sufrir tanto jaja. Gracias a ambos denuevo!

**Comment by lopezjurip** [comment]
Acabo de probar con `choco` y funciona bien. Solo hay que asegurarse de reiniciar la consola para tener acceso a los comandos `irb` y `gem`.
