### ISSUE TITLE
Gema Devise

### ISSUE THREAD

**Issue by TheDG** [IIC2513-2015-2/syllabus#7]
Se puede usar la gema Devise para autentificar acciones?

**Comment by ThomasHepner-zz** [comment]
No, lo siento. La idea es que uds. hagan esto a mano (con Devise sale altiro). Hay un RailsCast creo para lo de las autenticaciones, prueba viéndolo ahí. Saludos.

**Comment by wachunei** [comment]
Busquen `has_secure_password`, y como dice Thomas el RailsCast #250 les puede servir como referencia.

**Comment by lopezjurip** [comment]
También pueden ver el proyecto de ejemplo que @raulmt va actualizando cada clase.
https://github.com/IIC2513-2015-2/initiatiweb/commits/master
