### ISSUE TITLE
Variables de entorno

### ISSUE THREAD

**Issue by saratscheff** [IIC2513-2015-2/syllabus#8]
No me quedó claro el como utilizar las variables de entorno, conceptualmente quedó clarísimo, pero ¿Se podría repetir los pasos para configurar las variables de entorno en el sistema operativo? (Asignar las variables)

Gracias!

**Comment by lopezjurip** [comment]
Para asignar una variable de entorno para la sesión actual de la terminal:

``` sh
export VARIABLE="macoy123"
```

Si quieres que perdure cuando reinicias el computador tienes que escribir esa misma linea en `~/.bashrc` si usas Bash o en `~/.zshrc` si usas Zsh.

Se puede hacer de otras formas, no sé si alguien de acá sabrá una mejor.

**Comment by saratscheff** [comment]
Gracias!!
¿Y cómo se si uso ~/.bashrc o ~/.zshrc ? 
(¿O donde lo defino? ¿Los puedo usar ambas indistintamente?)

**Comment by wachunei** [comment]
Esos archivos están en el directorio `~`, si haces `$ cd ~` te va a llevar ahí, entonces (desde ahí) si haces `$ cat .bashrc` puedes ver su contenido ( o `$ cat .zshrc`).

Esos los debes editar, pero por ejemplo yo tengo un archivo `~/.aliases` con distintos alias y simplemento agrego la línea 

``` sh
. ~/.aliases
```

a mi archivo `~/.zshrc` y se ejecuta lo que esté dentro de ese archivo, el tuyo podría ser `~/.variables`.

Ah, depende de la shell que uses si usas bash o zsh, pero si agregas el archivo a ambos, en los dos van a estar las variables definidas.

**Comment by saratscheff** [comment]
Genial!! Muchas gracias!

**Comment by raulmt** [comment]
En todo caso, para este contexto de necesitar variables de entorno para un proyecto, lo otra opción que les mencioné en clases hoy es usar variables de entorno que se activen sólo en un directorio. Eso lo puedes hacer con [`direnv`](http://direnv.net/). Si usas linux, estará en tu manejador de paquetes (apt-get/aptitude/yum/etc), y su usas OSX lo puedes encontrar en [brew](http://brew.sh/). Esencialmente implica crear un archivo `.envrc` en el directorio raíz del proyecto, y escribir los export ahí. Cada vez que hagas cd al directorio se cargará `.envrc` y se "descargará" cuando cambies a otro directorio.

**Comment by saratscheff** [comment]
Perfecto! Gracias!!
